---
- name: Initial setup for Paperless backup using Restic
  hosts: playground
  become: true
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: patrick
  vars_files:
    - ./group_vars/vars.yml
    - ./group_vars/vault

  tasks:

    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Update arch system (using yay)
      aur:
        use: yay
        update_cache: true
        upgrade: true
      become: true
      become_user: aur_builder

    - name: Install restic (using yay)
      aur:
        use: yay
        name:
          - restic
      become: true
      become_user: aur_builder

    # Note: The `item|basename|regex` strips the `j2` extension. Found here: https://serverfault.com/a/640139
    - name: Copy ssh and backup scripts
      become: true
      become_user: root
      ansible.builtin.template:
        src: "{{ item }}"
        dest: /home/{{ paperless_user }}/paperless-ngx/{{ item | basename | regex_replace(' \.j2$', '')}}
        mode: '0744'
      with_fileglob:
        - ./resources/backup-paperless-restic2nas.sh.j2
        - ./resources/ssh-copy-id-to-nas.sh.j2

    - name: Create SSH keypair (if it doesn't exist yet)
      become: true
      become_user: root
      community.crypto.openssh_keypair:
        path: ~/.ssh/id_rsa
        passphrase: ""
        comment: paperless_restic_sheep
    
    - name: Copy systemd service
      become: true
      become_user: root
      ansible.builtin.template:
        src: ./resources/systemd/backup-paperless.service.j2
        dest: /etc/systemd/system/backup-paperless.service
        mode: '0644'

    - name: Copy systemd timer
      become: true
      become_user: root
      ansible.builtin.copy:
        src: ./resources/systemd/backup-paperless.timer
        dest: /etc/systemd/system/backup-paperless.timer
        mode: '0644'

    - name: Copy restic password file to target
      become: true
      become_user: root
      ansible.builtin.template:
        src: ./resources/restic-pw.j2
        dest: /root/restic-pw
        mode: '0600'
      
    - name: Start and enable system.d timer for restic backup
      become: true
      become_user: root
      ansible.builtin.systemd:
        name: backup-paperless.timer
        state: started
        enabled: yes
